package com.forward.desk_resolver.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.domain.Persistable;

import java.time.Instant;
import java.util.UUID;

/**
 * A server-side record of one issued access token, which is what makes the token revocable.
 *
 * <p><strong>What this changes about the authentication model.</strong> Until now authentication was
 * purely stateless, and docs/DECISIONS.md recorded the consequence as an accepted limitation: a token
 * stayed valid for its full 30 minutes whatever happened to the account behind it. Logging out was a
 * client-side gesture, and a password change could not end a session someone already held.
 *
 * <p>A token now carries a {@code sid} claim naming a row in this table, and every authenticated
 * request resolves it. A session that is revoked, past {@link #expiresAt}, or belongs to a
 * deactivated user is a 401 on the next request. The signature and expiry checks still happen first,
 * so this is a second gate rather than a replacement for them.
 *
 * <p><strong>What it costs, and what it does not.</strong> One indexed lookup per authenticated
 * request - and it is the <em>same</em> query that resolves the caller's roles and permissions, which
 * previously came from a static map. So revocation did not add a round trip; it shares the one that
 * database-backed authorization already required. See {@code AuthContextLoader}.
 *
 * <p><strong>The id is a UUID generated by the application</strong>, not a sequence value. It travels
 * inside a token that reaches the client, and a sequential session identifier would be guessable and
 * countable. Generating it in Java also keeps session creation to a single insert with no round trip
 * for the key.
 *
 * <p>This is <em>not</em> an HTTP session: nothing is stored in it, no cookie exists, and the security
 * filter chain is still {@code STATELESS}. It is a revocation list, expressed positively.
 */
@Entity
@Table(name = "sessions", schema = "auth")
@Getter
@Setter
public class UserSession implements Persistable<UUID> {

    @Id
    @Column(name = "id", nullable = false)
    private UUID id;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Column(name = "issued_at", nullable = false)
    private Instant issuedAt;

    /** Kept equal to the token's {@code exp} claim, so neither can outlive the other. */
    @Column(name = "expires_at", nullable = false)
    private Instant expiresAt;

    /** Null while the session is live. Set once, never cleared - a session is not un-revoked. */
    @Column(name = "revoked_at")
    private Instant revokedAt;

    /** Why it was revoked; see {@code SessionService.RevocationReason}. Diagnostic, never authoritative. */
    @Column(name = "revoked_reason", length = 50)
    private String revokedReason;

    /**
     * The address the session was opened from, and the client that opened it.
     *
     * <p>Both are recorded for the sake of answering "where was this session used from" after the
     * fact, and neither is ever trusted for a decision - {@code user_agent} is client-supplied, and
     * {@code client_ip} is only as good as the deployment's proxy configuration (see
     * {@code ClientIpResolver}). Truncated to the column width on write rather than risking a
     * failed login over an overlong header.
     */
    @Column(name = "client_ip", length = 64)
    private String clientIp;

    @Column(name = "user_agent", length = 255)
    private String userAgent;

    /**
     * Whether this instance has yet to be written.
     *
     * <p><strong>Why {@link Persistable} is implemented at all.</strong> The id is assigned by the
     * application rather than generated by the database, and Spring Data decides between
     * {@code persist} and {@code merge} by asking whether the id is null. With an assigned id it is
     * never null, so every {@code save} of a brand-new session would be a {@code merge}: a SELECT to
     * look for a row that cannot exist, followed by the INSERT. That is one wasted round trip on the
     * login path, for nothing.
     *
     * <p>Answering the question directly removes it. The flag starts true, and is cleared once the row
     * has been written or loaded, so a session read back and revoked still updates rather than
     * attempting a second insert.
     */
    @Transient
    private boolean unsaved = true;

    @Override
    public boolean isNew() {
        return unsaved;
    }

    @PostPersist
    @PostLoad
    void markSaved() {
        this.unsaved = false;
    }
}
